### PR TITLE
chore: remove frontend-lib-content-components from workflow [FC-0062]

### PR DESCRIPTION
**Pull request by bradenmacdonald**
We've moved [frontend-lib-content-components](https://github.com/openedx/frontend-lib-content-components) into [frontend-app-course-authoring](https://github.com/openedx/frontend-app-course-authoring/), so we don't need to extract translations from content-components any more.

Related PR: https://github.com/openedx/frontend-app-course-authoring/pull/1208

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bradenmacdonald!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@committers-translations`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Review by OmarIthawi — CHANGES_REQUESTED** [review]
Thanks @bradenmacdonald! Always a pleasure to review your PRs :)

Please also remove 

https://github.com/openedx/openedx-translations/blob/d654700108a145bb862560cb9d71c9c875de7135/transifex.yml#L256-L262

Alsp remove to the actual resource translations (sorry for chaning my mind mid-way). Removing the actual resources won't break the [`Makefile`](https://github.com/search?q=org%3Aopenedx+frontend-lib-content-components+language%3AMakefile&type=code&l=Makefile) scripting because it just ignores empty or missing files.

However, there's a ton of [references for the `frontend-lib-content-components`](https://github.com/search?q=org%3Aopenedx%20frontend-lib-content-components&type=code) that should be taken care of including a questionalbe reference in the communications app.

I hope you're aware of the rabbit hole. Nevertheless, thank you for taking the time to refactor.

**Comment by bradenmacdonald** [comment]
@OmarIthawi Thanks - done!

> Alsp remove to the actual resource translations (sorry for chaning my mind mid-way). Removing the actual resources won't break the [Makefile](https://github.com/search?q=org%3Aopenedx+frontend-lib-content-components+language%3AMakefile&type=code&l=Makefile) scripting because it just ignores empty or missing files.

I'm not sure what you'd like me to do for this, sorry. Is that something to do in Transifex itself? If so I'm not sure if I even have permission.

> However, there's a ton of [references for the frontend-lib-content-components](https://github.com/search?q=org%3Aopenedx%20frontend-lib-content-components&type=code) that should be taken care of including a questionalbe reference in the communications app.

Good point. I will open some more PRs to update those various references.

**Comment by OmarIthawi** [comment]
> I'm not sure what you'd like me to do for this, sorry. Is that something to do in Transifex itself? If so I'm not sure if I even have permission.
> 
> >

Appologies. Please remove this directory from the repository:

 - https://github.com/openedx/openedx-translations/tree/main/translations/frontend-lib-content-components

All of it, including both source strings and the translations.

**Review by OmarIthawi — APPROVED** [review]
Looks great! Thanks @bradenmacdonald!

**Comment by openedx-webhooks** [comment]
@bradenmacdonald 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/7070&entry.1484655318=https://github.com/bradenmacdonald&entry.752974735=2024-08-29+18:53&entry.1917517419=2024-08-29+23:02&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
