### PR TITLE
feat: extract from edx-platform

### PR DESCRIPTION
**Pull request by OmarIthawi**
### Changes

 - Add the `edx-platform` to the `python-translations` job
 - Support caching in _vein attempt_ to reduce the edx-platform setup time from 4 minutes to 3 minutes
 - Added multiple preps to ensure `base.txt` compiles and the edx-platform behaves more normally
 - Split `extract translation source files` into multiple steps to accommodate for edX Platform multi-file setup

### Suggestions

 - Do we really need the `mako.po`, `studio.po` etc split, looking back, it seems to be complicating the i18n? I'm saying this because named-releases are already doing fine with just two big `django.po` and `djangojs.po` files: 
   - https://github.com/openedx/edx-platform/pull/32994

### TODO
 - [x] Tested on my fork and it seems to be working correctly: https://github.com/Zeit-Labs/openedx-translations/pull/61/commits/8838d06d69ed769a280f7f761749b04eaece4336
 - [x] Use the combined `django.po` and `djangojs.po` as suggested: https://github.com/openedx/edx-platform/pull/32994

---

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by OmarIthawi** [comment]
@shadinaif please take over this pull request and close it.

**Comment by shadinaif** [comment]
I've [taken over](https://github.com/openedx/openedx-translations/pull/1275) the PR @OmarIthawi , you can close this one

**Comment by OmarIthawi** [comment]
Thanks @shadinaif! Closed.

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/541&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-08-13+16:02&entry.1917517419=2023-09-28+07:30&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/541&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-08-13+16:02&entry.1917517419=2023-09-28+07:30&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
