### PR TITLE
fix: edx-platform django-mptt python 3.8 compatibility

### PR DESCRIPTION
**Pull request by OmarIthawi**
Bump to python 3.9, which later needs another bump to 3.11

### TODO

 - [ ] Test on edx-platform: https://github.com/openedx/openedx-translations/actions/runs/9497729190

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @OmarIthawi! Is this still in progress?

**Comment by OmarIthawi** [comment]
Still in progress. I'll mark as draft.

**Comment by OmarIthawi** [comment]
closing in favor of #7152

**Pull request closed without merging**
