### PR TITLE
chore: add sample translations to learning MFE, header and footer

### PR DESCRIPTION
**Pull request by OmarIthawi**
Added sample translations from transifex manually to:

 - frontend-app-learning
 - frontend-component-footer
 - frontend-component-header

This helps to test the Atlas automation for the learning MFE.

References
----------

This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Check the links above for full information about the overall project.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by brian-smith-tcril** [comment]
I don't think it makes sense to manually add sample translations to `main` here. If there's a need for sample translations that can't be addressed by using a fork, then we can consider making a new branch on this repo where sample/test translations can live.

The idea is for the `main` branch here to be a "source of truth" for current translations as they exist in transifex. If I'm mistaken in thinking this PR breaks that please let me know.

**Comment by OmarIthawi** [comment]
> I don't think it makes sense to manually add sample translations to `main` here. If there's a need for sample translations that can't be addressed by using a fork, then we can consider making a new branch on this repo where sample/test translations can live.
> 
> The idea is for the `main` branch here to be a "source of truth" for current translations as they exist in transifex. If I'm mistaken in thinking this PR breaks that please let me know.

@brian-smith-tcril Those translations are pulled from the repositories `frontend-app-learning`, `frontend-component-header`/`footer` so they're true real translations in that sense. They're also _indirectly_ pulled from Transifex. The notable issue is that they'll be outdated compared to Transifex.

The better alternative to this PR is to setup automation to add translations from GitHub to this repo, which I don't have access to. But my initial thought was that the translations would be overwritten hence up to date once we have Transifex bot is configured.

**Comment by OmarIthawi** [comment]
> My concern is that we already have the transifex github app set up for frontend-component-header and frontend-component-footer

Makes sense @brian-smith-tcril this is a band-aid indeed. I'll close this PR unmerged, but let's double-check few things before I do so.

> We should be getting autogenerated PRs with translations (similar to https://github.com/openedx/openedx-translations/pull/139)
> if that's not happening, we should really address the root cause there instead of manually adding translations as a band-aid

I don't think this is happening. #139 is for English source translation files, and we need to add some translations from Transifex for other languages which I don't see it setup.

I did the following check:

**List all non-English files**
```
openedx-translations $ git ls-files translations/ | grep -v -e transifex_input.json -e conf/locale/en/
translations/credentials/credentials/conf/locale/fr_CA/LC_MESSAGES/django.po
translations/credentials/credentials/conf/locale/fr_CA/LC_MESSAGES/djangojs.po
```

**Check the history of those files**

```
openedx-translations $ git log translations/credentials/credentials/conf/locale/fr_CA
commit 596cc6dc037799d3b0e28951556819ef3e585721
Author: Carlos Muniz <cmuniz@tcril.org>
Date:   Thu Jan 19 10:32:49 2023 -0500

    refactor: move translations files to intermediate directory (#77)
    
    * refactor: move translations files to intermediate
    
    An intermediate directory `translations` has been created to contain the
    directories containing translations files generated from the openedx
    repositories. Files will be better organized in this intermediate
    directory.
    
    * fix: remove unnecessary "/" from src
```

It looks like a manual addition, so it looks like we need to find a way to add translations from Transifex to this repository.

I don't think I have the needed access rights, but I'm happy to write `.github` workflow files. I need to review the Transifex official new GitHub workflow first.

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/161&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-03-28+00:34&entry.1917517419=2023-04-06+15:29&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
