### PR TITLE
feat: extract translations from frontend-app-ora

### PR DESCRIPTION
**Pull request by nsprenkle**
Add [frontend-app-ora](https://github.com/openedx/frontend-app-ora) to list of MFEs with openedx-translation-managed translations.

### CODE REVIEW

**Comment by nsprenkle** [comment]
> Thank you so much for this PR! Would you be able to verify the change to `extract-translations-source-files` is working on your fork? If you have actions enabled on your fork you should be able to visit https://github.com/nsprenkle/openedx-translations/actions/workflows/extract-translation-source-files.yml and see a `workflow_dispatch` trigger
> 
> image

Hey @brian-smith-tcril , none of the workflows here transferred over to my fork. Is there a standard process to get these set up?

**Comment by nsprenkle** [comment]
Okay, @brian-smith-tcril , I did a bit of research and troubleshooting but figured it out. Capturing what I found here for folks who may run into something similar.

1. GitHub actions (by default) only run on `main`/`master. I had to merge my changes into [main](https://github.com/nsprenkle/openedx-translations/commits/main/) to get the workflows to show up.
2. I had to modify the `.github/workflows/extract-translation-source-files.yml` file (see https://github.com/nsprenkle/openedx-translations/commit/67d4a9ef0a2ba6dedd165aac5410432f70c30e35) to get the runner to pick up from the [openedx](https://github.com/openedx) org instead of my personal account.

After those, I was then able to successfully run the workflow creating [these files](https://github.com/nsprenkle/openedx-translations/tree/automated/extract-translation-source-files-20241121T174520/translations/frontend-app-ora/src/i18n) on [this new branch ](https://github.com/nsprenkle/openedx-translations/tree/automated/extract-translation-source-files-20241121T174520).

**My question:** is success in running that job all that is needed for verification?

**Review by brian-smith-tcril — APPROVED** [review]
Thank you so much for writing up the changes you needed to make to verify it on your fork! It looks like the generated file is valid and the path matches the one you added to `transifex.yml` so this should be good to go!

**Comment by nsprenkle** [comment]
> Thank you so much for writing up the changes you needed to make to verify it on your fork! It looks like the generated file is valid and the path matches the one you added to `transifex.yml` so this should be good to go!

Excellent, thanks for checking back in, @brian-smith-tcril. 

I'm unable to merge so are you able to merge this PR?

**Pull request merged**
