### PR TITLE
feat: Add xblock-drag-and-drop-v2 to the translation pipeline

### PR DESCRIPTION
**Pull request by shadinaif**
feat: Add xblock-drag-and-drop-v2 to the translation pipeline

**IMPORTANT**: This PR needs https://github.com/openedx/xblock-drag-and-drop-v2/pull/316 before it's merged.

Refs: see details [here](https://github.com/openedx/xblock-drag-and-drop-v2/pull/316)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shadinaif!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@mphilbrick211 tests passed.

**Comment by itsjeyd** [comment]
@shadinaif Just a friendly reminder to resolve merge conflicts here.

**Comment by shadinaif** [comment]
Done @itsjeyd , thanks for the reminder. This must wait for https://github.com/openedx/xblock-drag-and-drop-v2/pull/316 to be merged

**Comment by itsjeyd** [comment]
@shadinaif Noted, thanks. Changing status to Blocked for now.

**Comment by itsjeyd** [comment]
@shadinaif Looks like this is unblocked now (https://github.com/openedx/xblock-drag-and-drop-v2/pull/316 has been merged, and build is green 🎉)! Marking as ready for review.

@openedx/axim-engineering This PR is ready for engineering review.

CC @mphilbrick211

**Comment by sarina** [comment]
FYI @itsjeyd - this is part of FC-12 and you should tag @brian-smith-tcril rather than the whole eng team on that.

@shadinaif could you be sure to put "FC-12" in the PR title or description?

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@shadinaif 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/146&entry.1484655318=https://github.com/shadinaif&entry.752974735=2023-03-13+14:24&entry.1917517419=2023-04-20+15:09&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
