### PR TITLE
chore: rename transifex-resources.ini file and upgrade deps

### PR DESCRIPTION
**Pull request by OmarIthawi**
This is a noisy chore commit that is intended to prep for other Transifex workflows.

-----

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by brian-smith-tcril** [comment]
> This is a on-demand GitHub Actions workflow which will sync translations and their status from the open-edx/edx-platform Transifex project (old) into open-edx/openedx-translations OEP-58 project (new).

I don't see any changes to workflows in this PR, was this line in the description copied from https://github.com/openedx/openedx-translations/pull/569?

**Comment by OmarIthawi** [comment]
> I don't see any changes to workflows in this PR, was this line in the description copied from #569?

Good catch @brian-smith-tcril, now removed.

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/570&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-08-20+12:48&entry.1917517419=2023-08-22+13:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
