### PR TITLE
feat: Add platform-plugin-aspects repo to translations

### PR DESCRIPTION
**Pull request by bmtcril**
It's been a while since I've done one of these, so it's entirely possible I missed a step here.

### CODE REVIEW

**Comment by bmtcril** [comment]
@brian-smith-tcril I've tested this on a fork against latest platform-plugin-aspects and I think it should be good to go now.

**Review by OmarIthawi — APPROVED** [review]
LGTM.

**Comment by OmarIthawi** [comment]
@bmtcril I suppose you've already followed the testing steps here:

 - https://docs.openedx.org/en/latest/developers/how-tos/enable-translations-new-repo.html#testing-and-debugging

It makes me think that we should add it to the pull request template.

**Comment by bmtcril** [comment]
I think those directions are a little out of date, but I did test extract_translations in my fork against the new repo

**Pull request merged**
