### PR TITLE
fix: non-relevant directories are added if conf/locale is missing

### PR DESCRIPTION
**Pull request by shadinaif**
When python-translations is processed; we can have non-relevant directories added to the translation directory if `make extract_translations` did not generate the proper English directory at conf/locale

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shadinaif!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by shadinaif** [comment]
@OmarIthawi @brian-smith-tcril please review

**Review by OmarIthawi — COMMENTED** [review]
@shadinaif Looks like a great addition, thanks! 

Please test it on a fork and share the results.

**Comment by shadinaif** [comment]
As you can see [here](https://github.com/Zeit-Labs/openedx-translations/actions/runs/5608878290/jobs/10261831013) @OmarIthawi , `master` branch of `credentials-themes` caused it to fail because it's not complying with the correct path for `locale\en`. While `DoneXBlock` passed normally

**Review by OmarIthawi — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@shadinaif 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/385&entry.1484655318=https://github.com/shadinaif&entry.752974735=2023-06-10+10:40&entry.1917517419=2023-07-22+17:23&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by OmarIthawi** [comment]
Thanks @shadinaif!! Merged :)

**Pull request merged**
