### PR TITLE
feat: sync from old transifex project

### PR DESCRIPTION
**Pull request by OmarIthawi**
This is a on-demand GitHub Actions workflow which will sync traslations and their status from the `open-edx/edx-platform` Transifex project (old) into `open-edx/openedx-translations` OEP-58 project (new).

This is to address [@ghassanmas's recommendation](https://github.com/openedx/edx-platform/pull/32994#issuecomment-1680054505) on preserving the translated/reviewed status when migrating to the new project.

### TODO

 - [x] Merge #570 first, then merge this PR
 - [ ] Run `make TX_LANGUAGES=ar SYNC_ARGS='--dry-run' sync_translations_github_workflow` to ensure resource slugs are correct
 - [ ] Ensure that plural messages translations are synced from old project
 - [ ] Test on few resources
 - [ ] Enable the rest of the resources

-----

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by shadinaif** [comment]
it's charming @OmarIthawi , thank you! I've pushed a small fix for your review and squash. I also posted on slack the issues found when comparing the original and the new transifex resources

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/569&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-08-20+12:39&entry.1917517419=2023-09-18+09:15&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/569&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-08-20+12:39&entry.1917517419=2023-09-18+09:15&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
